/**
 * Mule GitHub Connector
 *
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */

/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.mule.modules;

import org.eclipse.egit.github.core.Issue;
import org.eclipse.egit.github.core.Key;
import org.eclipse.egit.github.core.Repository;
import org.eclipse.egit.github.core.RepositoryId;
import org.eclipse.egit.github.core.Team;
import org.eclipse.egit.github.core.User;
import org.eclipse.egit.github.core.service.IssueService;
import org.eclipse.egit.github.core.service.TeamService;
import org.eclipse.egit.github.core.service.UserService;
import org.junit.Before;
import org.junit.Test;
import org.mockito.ArgumentCaptor;
import org.mockito.Captor;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import static org.mockito.Matchers.eq;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.spy;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

public class GitHubModuleTest {

    private static final String REPOSITORY = "myRepo";
    private static final String USER = "pepe";
    private static final String ISSUE_ID = "321";
    private static final String LOGIN_NAME = "login name";
    private static final List<String> EMAILS = Arrays.asList("email1", "email2");
    private static final int KEY_ID = 6655;
    private static final int TEAM_ID = 5322;
    private static final String ORGANIZATION = "some org";
    private static final String TEAM_NAME = "some team name";
    private static final int ORG_ID = 12043;
    @Mock
    private IssueService issueService;
    @Mock
    private UserService userService;
    @Mock
    private TeamService teamService;
    @Mock
    private Issue issue1;
    @Mock
    private Issue issue2;
    @Mock
    private Key key1;
    @Mock
    private Key key2;
    @Mock
    private User user;
    @Mock
    private Repository repository;
    @Captor
    private ArgumentCaptor<Issue> issueCaptor;
    @Captor
    private ArgumentCaptor<Key> keyCaptor;
    @Captor
    private ArgumentCaptor<Team> teamCaptor;
    private Map<String, String> filterData = new HashMap<String, String>(1);
    private GitHubModule gitHubModule;
    @Mock
    private Team team1;
    @Mock
    private Team team2;

    @Before
    public void setUpTests() {
        MockitoAnnotations.initMocks(this);
        ServiceFactory.setDefaultIssueService(issueService);
        ServiceFactory.setDefaultUserService(userService);
        ServiceFactory.setDefaultTeamService(teamService);
        filterData = new HashMap<String, String>(1);
        filterData.put("status", "closed");
        gitHubModule = new GitHubModule();
        gitHubModule.setUser(USER);
    }

    @Test
    public void getIssues() throws Exception {
        List<Issue> issues = createList(issue1, issue2);
        when(issueService.getIssues(USER, REPOSITORY, filterData)).thenReturn(issues);
        assertEquals(issues, gitHubModule.getIssues(USER, REPOSITORY, filterData));
    }

    @Test
    public void getIssuesCretedAfter() throws Exception {
        List<Issue> issues = createList(issue1, issue2);
        when(issueService.getIssues(USER, REPOSITORY, Collections.<String, String>emptyMap())).thenReturn(issues);
        when(issue1.getCreatedAt()).thenReturn(new Date(System.currentTimeMillis() - 10 * 1000 * 60));
        when(issue2.getCreatedAt()).thenReturn(new Date());
        assertEquals(Arrays.asList(issue2), gitHubModule.getIssuesCretedAfter(USER, REPOSITORY, 1));
    }

    @Test
    public void getIssuesSinceNumber() throws Exception {
        List<Issue> issues = createList(issue1, issue2);
        when(issueService.getIssues(USER, REPOSITORY, Collections.<String, String>emptyMap())).thenReturn(issues);
        when(issue1.getNumber()).thenReturn(5);
        when(issue2.getNumber()).thenReturn(15);
        assertEquals(Arrays.asList(issue2), gitHubModule.getIssuesSinceNumber(USER, REPOSITORY, 10));
    }

    @Test
    public void createIssue() throws Exception {
        gitHubModule.createIssue(USER, REPOSITORY, "issue title", "issue body", "coco");
        verify(issueService).createIssue(eq(USER), eq(REPOSITORY), issueCaptor.capture());
        Issue issueSentToGitHub = issueCaptor.getValue();
        assertEquals("issue title", issueSentToGitHub.getTitle());
        assertEquals("issue body", issueSentToGitHub.getBody());
        assertEquals("coco", issueSentToGitHub.getAssignee().getName());
    }

    @Test
    public void closeIssue() throws Exception {
        GitHubModule gitHubModuleSpy = spy(gitHubModule);
        when(gitHubModuleSpy.getIssue(USER, REPOSITORY, ISSUE_ID)).thenReturn(issue1);
        gitHubModule.closeIssue(USER, REPOSITORY, ISSUE_ID);
        verify(issueService).editIssue(USER, REPOSITORY, issue1);
        verify(issue1).setState("closed");
    }

    @Test
    public void getIssue() throws Exception {
        when(issueService.getIssue(USER, REPOSITORY, ISSUE_ID)).thenReturn(issue1);
        assertEquals(issue1, gitHubModule.getIssue(USER, REPOSITORY, ISSUE_ID));
        verify(issueService).getIssue(USER, REPOSITORY, ISSUE_ID);
    }

    @Test
    public void getUserByLoginName() throws Exception {
        when(userService.getUser(LOGIN_NAME)).thenReturn(user);
        assertEquals(user, gitHubModule.getUserByLoginName(LOGIN_NAME));
    }

    @Test
    public void getCurrentUser() throws Exception {
        when(userService.getUser()).thenReturn(user);
        assertEquals(user, gitHubModule.getCurrentUser());
    }

    @Test
    public void updateCurrentUser() throws Exception {
        GitHubModule gitHubModuleSpy = spy(gitHubModule);
        when(gitHubModuleSpy.getCurrentUser()).thenReturn(user);
        User updatedUser = mock(User.class);
        when(userService.editUser(user)).thenReturn(updatedUser);
        assertEquals(updatedUser, gitHubModule.updateCurrentUser("new name", "new email", "new blog", "new company", "new location", true));
        verify(user).setName("new name");
        verify(user).setEmail("new email");
        verify(user).setBlog("new blog");
        verify(user).setCompany("new company");
        verify(user).setLocation("new location");
        verify(user).setHireable(true);
    }

    @Test
    public void getFollowers() throws Exception {
        List<User> followers = Arrays.asList(user);
        when(userService.getFollowers(USER)).thenReturn(followers);
        assertEquals(followers, gitHubModule.getFollowers(null));
    }

    @Test
    public void isFollowing() throws Exception {
        when(userService.isFollowing("some user")).thenReturn(true);
        assertTrue(gitHubModule.isFollowing("some user"));
    }

    @Test
    public void follow() throws Exception {
        gitHubModule.follow("some user");
        verify(userService).follow("some user");
    }

    @Test
    public void unfollow() throws Exception {
        gitHubModule.unfollow("some user");
        verify(userService).unfollow("some user");
    }

    @Test
    public void getEmails() throws Exception {
        when(userService.getEmails()).thenReturn(EMAILS);
        assertEquals(EMAILS, gitHubModule.getEmails());
    }

    @Test
    public void addEmails() throws Exception {
        gitHubModule.addEmails(EMAILS);
        verify(userService).addEmail((String[]) EMAILS.toArray());
    }

    @Test
    public void removeEmails() throws Exception {
        gitHubModule.removeEmails(EMAILS);
        verify(userService).removeEmail((String[]) EMAILS.toArray());
    }

    @Test
    public void getKeys() throws Exception {
        List<Key> keys = Arrays.asList(key1, key2);
        when(userService.getKeys()).thenReturn(keys);
        assertEquals(keys, gitHubModule.getKeys());
    }

    @Test
    public void getKey() throws Exception {
        when(userService.getKey(KEY_ID)).thenReturn(key1);
        assertEquals(key1, gitHubModule.getKey(KEY_ID));
    }

    @Test
    public void createKey() throws Exception {
        gitHubModule.createKey("key title", "key");
        verify(userService).createKey(keyCaptor.capture());
        Key keySentToGitHub = keyCaptor.getValue();
        assertEquals("key title", keySentToGitHub.getTitle());
        assertEquals("key", keySentToGitHub.getKey());
    }

    @Test
    public void editKey() throws Exception {
        GitHubModule gitHubModuleSpy = spy(gitHubModule);
        when(gitHubModuleSpy.getKey(KEY_ID)).thenReturn(key1);
        when(userService.editKey(key1)).thenReturn(key2);
        assertEquals(key2, gitHubModule.editKey(KEY_ID, "new title", "new key"));
        verify(key1).setTitle("new title");
        verify(key1).setKey("new key");
    }

    @Test
    public void getTeam() throws Exception {
        when(teamService.getTeam(TEAM_ID)).thenReturn(team1);
        assertEquals(team1, gitHubModule.getTeam(TEAM_ID));
    }

    @Test
    public void getTeamsForOrg() throws Exception {
        List<Team> teams = Arrays.asList(team1, team2);
        when(teamService.getTeams(ORGANIZATION)).thenReturn(teams);
        assertEquals(teams, gitHubModule.getTeamsForOrg(ORGANIZATION));
    }

    @Test
    public void createTeam() throws Exception {
        List<String> repos = Arrays.asList("repo1", "repo2");
        gitHubModule.createTeam(ORGANIZATION, TEAM_NAME, TeamPermission.ADMIN, repos);
        verify(teamService).createTeam(eq(ORGANIZATION), teamCaptor.capture(), eq(repos));
        Team teamSentToGitHub = teamCaptor.getValue();
        assertEquals(TEAM_NAME, teamSentToGitHub.getName());
        assertEquals(TeamPermission.ADMIN.toString(), teamSentToGitHub.getPermission());
    }

    @Test
    public void editTeam() throws Exception {
        GitHubModule gitHubModuleSpy = spy(gitHubModule);
        when(gitHubModuleSpy.getTeam(TEAM_ID)).thenReturn(team1);
        gitHubModule.editTeam(TEAM_ID, TEAM_NAME, TeamPermission.ADMIN);
        verify(teamService).editTeam(team1);
        verify(team1).setName(TEAM_NAME);
        verify(team1).setPermission(TeamPermission.ADMIN.toString());
    }

    @Test
    public void deleteTeam() throws Exception {
        gitHubModule.deleteTeam(TEAM_ID);
        verify(teamService).deleteTeam(TEAM_ID);
    }

    @Test
    public void getMembers() throws Exception {
        List<User> teamMembers = Arrays.asList(user);
        when(teamService.getMembers(TEAM_ID)).thenReturn(teamMembers);
        assertEquals(teamMembers, gitHubModule.getTeamMembers(TEAM_ID));
    }

    @Test
    public void isTeamMember() throws Exception {
        when(teamService.isMember(TEAM_ID, USER)).thenReturn(true);
        assertTrue(gitHubModule.isTeamMember(TEAM_ID, USER));
    }

    @Test
    public void addTeamMember() throws Exception {
        gitHubModule.addTeamMember(TEAM_ID, USER);
        verify(teamService).addMember(TEAM_ID, USER);
    }

    @Test
    public void removeTeamMember() throws Exception {
        gitHubModule.removeTeamMember(TEAM_ID, USER);
        verify(teamService).removeMember(TEAM_ID, USER);
    }

    @Test
    public void getTeamRepositories() throws Exception {
        List<Repository> repos = Arrays.asList(repository);
        when(teamService.getRepositories(TEAM_ID)).thenReturn(repos);
        assertEquals(repos, gitHubModule.getTeamRepositories(TEAM_ID));
    }

    @Test
    public void addTeamRepository() throws Exception {
        gitHubModule.addTeamRepository(TEAM_ID, "owner", "name");
        verify(teamService).addRepository(eq(TEAM_ID), eq(new RepositoryId("owner", "name")));
    }

    @Test
    public void removeTeamRepository() throws Exception {
        gitHubModule.removeTeamRepository(TEAM_ID, "owner", "name");
        verify(teamService).removeRepository(eq(TEAM_ID), eq(new RepositoryId("owner", "name")));
    }

    private <T> List<T> createList(T... elements) {
        List<T> result = new ArrayList<T>(elements.length);
        Collections.addAll(result, elements);
        return result;
    }
}