/**
 * Mule GitHub Connector
 *
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */

/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.mule.modules;

import org.eclipse.egit.github.core.Comment;
import org.eclipse.egit.github.core.CommitComment;
import org.eclipse.egit.github.core.Contributor;
import org.eclipse.egit.github.core.Download;
import org.eclipse.egit.github.core.DownloadResource;
import org.eclipse.egit.github.core.Gist;
import org.eclipse.egit.github.core.Issue;
import org.eclipse.egit.github.core.IssueEvent;
import org.eclipse.egit.github.core.Key;
import org.eclipse.egit.github.core.Label;
import org.eclipse.egit.github.core.Milestone;
import org.eclipse.egit.github.core.Repository;
import org.eclipse.egit.github.core.RepositoryBranch;
import org.eclipse.egit.github.core.RepositoryCommit;
import org.eclipse.egit.github.core.RepositoryId;
import org.eclipse.egit.github.core.RepositoryTag;
import org.eclipse.egit.github.core.Team;
import org.eclipse.egit.github.core.User;
import org.mule.api.annotations.Configurable;
import org.mule.api.annotations.Module;
import org.mule.api.annotations.Processor;
import org.mule.api.annotations.display.Password;
import org.mule.api.annotations.display.Placement;
import org.mule.api.annotations.param.Default;
import org.mule.api.annotations.param.Optional;

import java.io.IOException;
import java.util.Collections;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

/**
 * Generic module
 *
 * @author MuleSoft, Inc.
 */
@Module(name = "github", schemaVersion = "1.0")
public class GitHubModule {

    /**
     * The user name
     */
    @Configurable
    @Placement(order = 1)
    private String user;
    /**
     * The password
     */
    @Configurable
    @Placement(order = 2)
    @Password
    private String password;
    private ServiceFactory serviceFactory;

    public GitHubModule() {
        serviceFactory = new ServiceFactory(user, password);
    }

    /**
     * Get a list of {@link Issue} objects that match the specified filter data
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param user       the owner of the repository, leave empty to use {@link this#user}
     * @param repository the repostory name
     * @param filterData data to filter issues, if non is specified all issues will be returned
     * @return list of {@link Issue}
     * @throws java.io.IOException
     */
    @Processor
    public List<Issue> getIssues(@Optional String user, String repository, @Optional Map<String, String> filterData) throws IOException {
        if (filterData == null) {
            filterData = Collections.emptyMap();
        }
        return serviceFactory.getIssueService().getIssues(getUser(user), repository, filterData);
    }

    /**
     * Custom processor
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param user       the owner of the repository, leave empty to use {@link this#user}
     * @param repository the repository name
     * @param minutes    minutes
     * @return a list of {@link Issue}
     * @throws java.io.IOException
     */
    @Processor
    public List<Issue> getIssuesCretedAfter(@Optional String user, String repository, int minutes) throws IOException {
        List<Issue> issues = serviceFactory.getIssueService().getIssues(getUser(user), repository, Collections.<String, String>emptyMap());
        Iterator<Issue> iterator = issues.iterator();
        Date since = new Date(System.currentTimeMillis() - minutes * 60 * 1000);
        while (iterator.hasNext()) {
            if (since.after(iterator.next().getCreatedAt())) {
                iterator.remove();
            }
        }
        return issues;
    }

    /**
     * Custom processor
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param user            the owner of the repository, leave empty to use {@link this#user}
     * @param repository      the repository name
     * @param fromIssueNumber from issue number
     * @return a list of {@link Issue}
     * @throws java.io.IOException
     */
    @Processor
    public List<Issue> getIssuesSinceNumber(@Optional String user, String repository, int fromIssueNumber) throws IOException {
        List<Issue> issues = serviceFactory.getIssueService().getIssues(getUser(user), repository, Collections.<String, String>emptyMap());
        Iterator<Issue> iterator = issues.iterator();
        while (iterator.hasNext()) {
            if (fromIssueNumber >= iterator.next().getNumber()) {
                iterator.remove();
            }
        }
        return issues;
    }

    /**
     * Creates a GitHub issue
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param user       the owner of the repository, leave empty to use {@link this#user}
     * @param repository the repository name
     * @param title      the issues's title
     * @param body       the issuess's body
     * @param assignee   optionally specify a asignee for the issue
     * @return the newly created {@link Issue}
     * @throws java.io.IOException
     */
    @Processor
    public Issue createIssue(@Optional String user, String repository, String title, String body, @Optional String assignee) throws IOException {
        Issue issue = new Issue();
        issue.setTitle(title);
        issue.setBody(body);
        if (assignee != null) {
            User assigneeUser = new User().setName(assignee);
            issue.setAssignee(assigneeUser);
        }
        return serviceFactory.getIssueService().createIssue(getUser(user), repository, issue);
    }

    /**
     * Closes a GitHub issue
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param user       the owner of the repository, leave empty to use {@link this#user}
     * @param repository the repository name
     * @param issueId    the issues's id
     * @return the newly created {@link Issue}
     * @throws java.io.IOException
     */
    @Processor
    public Issue closeIssue(@Optional String user, String repository, String issueId) throws IOException {
        Issue issue = getIssue(getUser(user), repository, issueId);
        issue.setState("closed");
        return serviceFactory.getIssueService().editIssue(getUser(user), repository, issue);
    }

    /**
     * Get the issue represented by the given issueId
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param user       the owner of the repository, leave empty to use {@link this#user}
     * @param repository the repostory name
     * @param issueId    the id of the issue
     * @return a {@link Issue}
     * @throws java.io.IOException
     */
    @Processor
    public Issue getIssue(@Optional String user, String repository, String issueId) throws IOException {
        return serviceFactory.getIssueService().getIssue(getUser(user), repository, issueId);
    }

    /**
     * Get an issue's comments
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param user       the owner of the repository, leave empty to use {@link this#user}
     * @param repository the repostory name
     * @param issueId    the id of the issue
     * @return a list of {@link Comment}
     * @throws java.io.IOException
     */
    @Processor
    public List<Comment> getComments(@Optional String user, String repository, String issueId) throws IOException {
        return serviceFactory.getIssueService().getComments(getUser(user), repository, issueId);
    }

    /**
     * Create comment on specified issue id
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param user       the owner of the repository, leave empty to use {@link this#user}
     * @param repository the repostory name
     * @param issueId    the issue id
     * @param comment    the text of the comment
     * @return the created {@link Comment}
     * @throws java.io.IOException
     */
    @Processor
    public Comment createComment(@Optional String user, String repository, String issueId, String comment) throws IOException {
        return serviceFactory.getIssueService().createComment(getUser(user), repository, issueId, comment);
    }

    /**
     * Edits the body of the comment represented by the given comment id
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param user       the owner of the repository, leave empty to use {@link this#user}
     * @param repository the repostory name
     * @param commentId  the comment id
     * @param body       the new text of the comment
     * @return the created {@link Comment}
     * @throws java.io.IOException
     */
    @Processor
    public Comment editComment(@Optional String user, String repository, Long commentId, String body) throws IOException {
        Comment comment = serviceFactory.getIssueService().getComment(getUser(user), repository, commentId);
        comment.setBody(body);
        return serviceFactory.getIssueService().editComment(getUser(user), repository, comment);
    }

    /**
     * Delete the issue comment with the given id
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param user       the owner of the repository, leave empty to use {@link this#user}
     * @param repository the repostory name
     * @param commentId  the id of the comment to delete
     * @throws java.io.IOException
     */
    @Processor
    public void deleteComment(@Optional String user, String repository, String commentId) throws IOException {
        serviceFactory.getIssueService().deleteComment(getUser(user), repository, commentId);
    }

    /**
     * Get issue event for repository
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param user       the owner of the repository, leave empty to use {@link this#user}
     * @param repository the repostory name
     * @param eventId    the id of the event
     * @return a {@link IssueEvent}
     * @throws java.io.IOException
     */
    @Processor
    public IssueEvent getIssueEvent(@Optional String user, String repository, long eventId) throws IOException {
        return serviceFactory.getIssueService().getIssueEvent(getUser(user), repository, eventId);
    }

    /**
     * Get users watching given repository
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param owner the name of the user that owns the repository
     * @param name  the name of the repository
     * @return non-null but possibly empty list of users
     * @throws IOException
     */
    @Processor
    public List<User> getWatchers(String owner, String name) throws IOException {
        return serviceFactory.getWatcherService().getWatchers(RepositoryId.create(owner, name));
    }

    /**
     * Get repositories watched by the given user
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param user the user for which the get the watched repositories, leave empty to use {@link this#user}
     * @return non-null but possibly empty list of repositories
     * @throws IOException
     */
    @Processor
    public List<Repository> getWatched(@Optional String user) throws IOException {
        return serviceFactory.getWatcherService().getWatched(getUser(user));
    }

    /**
     * Is currently authenticated user watching given repository?
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param owner the name of the user that owns the repository
     * @param name  the name of the repository
     * @return true if watch, false otherwise
     * @throws IOException
     */
    @Processor
    public boolean isWatching(String owner, String name) throws IOException {
        return serviceFactory.getWatcherService().isWatching(RepositoryId.create(owner, name));
    }

    /**
     * Add currently authenticated user as a watcher of the given repository
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param owner the name of the user that owns the repository
     * @param name  the name of the repository
     * @throws IOException
     */
    @Processor
    public void watch(String owner, String name) throws IOException {
        serviceFactory.getWatcherService().watch(RepositoryId.create(owner, name));
    }

    /**
     * Remove currently authenticated user as a watcher of the given repository
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param owner the name of the user that owns the repository
     * @param name  the name of the repository
     * @throws IOException
     */
    @Processor
    public void unwatch(String owner, String name) throws IOException {
        serviceFactory.getWatcherService().unwatch(RepositoryId.create(owner, name));
    }

    /**
     * Returns the list of collaborators of the given repository
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param owner the name of the user that owns the repository
     * @param name  the name of the repository
     * @return non-null but possibly empty list of users
     * @throws IOException
     */
    @Processor
    public List<User> getCollaborators(String owner, String name) throws IOException {
        return serviceFactory.getCollaboratorService().getCollaborators(RepositoryId.create(owner, name));
    }

    /**
     * Returns whether the user is a collaborator of the given repository
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param owner the name of the user that owns the repository
     * @param name  the name of the repository
     * @param user  the user to consult if it's a collaborator or not, leave empty to use {@link this#user}
     * @return true if the user is a collaborator, false otherwise
     * @throws IOException
     */
    @Processor
    public boolean isCollaborator(String owner, String name, @Optional String user) throws IOException {
        return serviceFactory.getCollaboratorService().isCollaborator(RepositoryId.create(owner, name), getUser(user));
    }

    /**
     * Adds a collaborator to the given repository
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param owner the name of the user that owns the repository
     * @param name  the name of the repository
     * @param user  the user that's going to be added as a collaborator to the given repository, leave empty to use {@link this#user}
     * @throws IOException
     */
    @Processor
    public void addCollaborator(String owner, String name, @Optional String user) throws IOException {
        serviceFactory.getCollaboratorService().addCollaborator(RepositoryId.create(owner, name), getUser(user));
    }

    /**
     * Removes a collaborator from the given repository
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param owner the name of the user that owns the repository
     * @param name  the name of the repository
     * @param user  the user that's going to be removed as a collaborator from the given repository, leave empty to use {@link this#user}
     * @throws IOException
     */
    @Processor
    public void removeCollaborator(String owner, String name, @Optional String user) throws IOException {
        serviceFactory.getCollaboratorService().removeCollaborator(RepositoryId.create(owner, name), getUser(user));
    }

    /**
     * Returns a list of the commits for a given repository
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param owner the name of the user that owns the repository
     * @param name  the name of the repository
     * @return non-null but possibly empty list of repository commits
     * @throws IOException
     */
    @Processor
    public List<RepositoryCommit> getCommits(String owner, String name) throws IOException {
        return serviceFactory.getCommitService().getCommits(RepositoryId.create(owner, name));
    }

    /**
     * Returns all commits in given repository beginning at an optional commit SHA-1
     * and affecting an optional path.
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param owner the name of the user that owns the repository
     * @param name  the name of the repository
     * @param sha   an optional Sha or branch to start listing commits from
     * @param path  optional Only commits containing this file path will be returned
     * @return non-null but possibly empty list of repository commits
     * @throws IOException
     */
    @Processor
    public List<RepositoryCommit> getCommitsBySha(String owner, String name, @Optional String sha, @Optional String path) throws IOException {
        return serviceFactory.getCommitService().getCommits(RepositoryId.create(owner, name), sha, path);
    }

    /**
     * Returns a commit with given SHA-1 from given repository
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param owner the name of the user that owns the repository
     * @param name  the name of the repository
     * @param sha   Sha from comment
     * @return a commit for the given Sha and repository
     * @throws IOException
     */
    @Processor
    public RepositoryCommit getCommit(String owner, String name, String sha) throws IOException {
        return serviceFactory.getCommitService().getCommit(RepositoryId.create(owner, name), sha);
    }

    /**
     * Returns all comments on commit with given Sha
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param owner the name of the user that owns the repository
     * @param name  the name of the repository
     * @param sha   Sha or branch to start listing commits comments from
     * @return non-null but possibly empty list of commits comments
     * @throws IOException
     */
    @Processor
    public List<CommitComment> getCommmitComments(String owner, String name, String sha) throws IOException {
        return serviceFactory.getCommitService().getComments(RepositoryId.create(owner, name), sha);
    }

    /**
     * Returns a comment from commit with the given id
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param owner     the name of the user that owns the repository
     * @param name      the name of the repository
     * @param commentId id from the comment
     * @return a commit that corresponds to the given id
     * @throws IOException
     */
    @Processor
    public CommitComment getComment(String owner, String name, long commentId) throws IOException {
        return serviceFactory.getCommitService().getComment(RepositoryId.create(owner, name), commentId);
    }

    /**
     * Creates a commit comment
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param owner    the name of the user that owns the repository
     * @param name     the name of the repository
     * @param body     Body of the commit comment
     * @param commitId Sha of the commit to comment on
     * @param line     line number in the file to comment on
     * @param path     relative path of the file to comment on
     * @param position line index in the diff to comment on
     */
    @Processor
    public void addComment(String owner, String name, String body, String commitId, int line, String path, int position) throws IOException {
        CommitComment comment = new CommitComment();
        comment.setCommitId(commitId);
        comment.setLine(line);
        comment.setPath(path);
        comment.setPosition(position);
        comment.setBody(body);

        serviceFactory.getCommitService().addComment(RepositoryId.create(owner, name), commitId, comment);
    }

    /**
     * Edits a given comment
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param owner    the name of the user that owns the repository
     * @param name     the name of the repository
     * @param body     Body of the commit comment
     * @param commitId Sha of the commit to comment on
     * @param line     line number in the file to comment on
     * @param path     relative path of the file to comment on
     * @param position line index in the diff to comment on
     */
    @Processor
    public void editCommitComment(String owner, String name, String body, String commitId, int line, String path, int position) throws IOException {
        CommitComment comment = new CommitComment();
        comment.setCommitId(commitId);
        comment.setLine(line);
        comment.setPath(path);
        comment.setPosition(position);
        comment.setBody(body);

        serviceFactory.getCommitService().editComment(RepositoryId.create(owner, name), comment);
    }

    /**
     * Deletes the given comment
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param owner     the name of the user that owns the repository
     * @param name      the name of the repository
     * @param commentId id from the comment
     * @throws IOException
     */
    @Processor
    public void deleteCommitComment(String owner, String name, long commentId) throws IOException {
        serviceFactory.getCommitService().deleteComment(RepositoryId.create(owner, name), commentId);
    }

    /**
     * Returns all deploys keys associated with the given repository
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param owner the name of the user that owns the repository
     * @param name  the name of the repository
     * @return non-null but possibly empty list of keys
     * @throws IOException
     */
    @Processor
    public List<Key> getDeployKeys(String owner, String name) throws IOException {
        return serviceFactory.getDeployKeyService().getKeys(RepositoryId.create(owner, name));
    }


    /**
     * Returns the key that corresponds to the given id
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param owner the name of the user that owns the repository
     * @param name  the name of the repository
     * @param id    the id of the key
     * @return the key corresponding to the given id
     * @throws IOException
     */
    @Processor
    public Key getDeployKey(String owner, String name, int id) throws IOException {
        return serviceFactory.getDeployKeyService().getKey(RepositoryId.create(owner, name), id);
    }


    /**
     * Returns a new deploy key
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param owner the name of the user that owns the repository
     * @param name  the name of the repository
     * @param title the title of the key
     * @param key   ssh key
     * @return a new Key created based on the given parameters
     * @throws IOException
     */
    @Processor
    public Key createDeployKey(String owner, String name, String title, String key) throws IOException {
        Key k = new Key();
        k.setTitle(title);
        k.setKey(key);
        return serviceFactory.getDeployKeyService().createKey(RepositoryId.create(owner, name), k);
    }

    /**
     * Edits a given deploy key
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param owner the name of the user that owns the repository
     * @param name  the name of the repository
     * @param title the title of the key
     * @param key   ssh key
     * @return the modified deploy key
     * @throws IOException
     */
    @Processor
    public Key editDeployKey(String owner, String name, String title, String key) throws IOException {
        Key k = new Key();
        k.setTitle(title);
        k.setKey(key);
        return serviceFactory.getDeployKeyService().editKey(RepositoryId.create(owner, name), k);
    }


    /**
     * Deletes a deploy key given the given id
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param owner the name of the user that owns the repository
     * @param name  the name of the repository
     * @param id    the id of the deploy key
     * @throws IOException
     */
    @Processor
    public void deleteDeployKey(String owner, String name, int id) throws IOException {
        serviceFactory.getDeployKeyService().deleteKey(RepositoryId.create(owner, name), id);
    }

    /**
     * Returns a single download given the provided id
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param owner the name of the user that owns the repository
     * @param name  the name of the repository
     * @param id    the id of the download
     * @return the download corresponding to the given id
     * @throws IOException
     */
    @Processor
    public Download getDownload(String owner, String name, int id) throws IOException {
        return serviceFactory.getDownloadService().getDownload(RepositoryId.create(owner, name), id);
    }

    /**
     * Deletes a download given the provided id
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param owner the name of the user that owns the repository
     * @param name  the name of the repository
     * @param id    the id of the download
     * @throws IOException
     */
    @Processor
    public void deleteDownload(String owner, String name, int id) throws IOException {
        serviceFactory.getDownloadService().deleteDownload(RepositoryId.create(owner, name), id);
    }

    /**
     * Creates a new download resource
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param owner        the name of the user that owns the repository
     * @param name         the name of the repository
     * @param resourceName the name of the resource
     * @param size         the size of the resource
     * @param description  an optional description
     * @param contentType  an optional content type
     * @return a new download resource
     * @throws IOException
     */
    @Processor
    public DownloadResource createResource(String owner, String name, String resourceName, long size, @Optional String description, @Optional String contentType) throws IOException {
        Download download = new Download();
        download.setName(resourceName);
        download.setSize(size);
        download.setDescription(description);
        download.setContentType(contentType);
        return serviceFactory.getDownloadService().createResource(RepositoryId.create(owner, name), download);
    }

    //TODO add upload resource and missing create download methods

    /**
     * Returns the gist according to the given id
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param id id of the wanted gist
     * @return returns the gist according to the provided id
     * @throws IOException
     */
    @Processor
    public Gist getGist(String id) throws IOException {
        return serviceFactory.getGistService().getGist(id);
    }

    /**
     * Returns the starred gists for the currently authenticated user
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @return list of starred gists for currently authenticated user
     * @throws IOException
     */
    @Processor
    public List<Gist> getStarredGist() throws IOException {
        return serviceFactory.getGistService().getStarredGists();
    }

    /**
     * Returns a list of gists for the specified user
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param user user of the gists, leave empty to use {@link this#user}
     * @return a list of gists for the specified user
     * @throws IOException
     */
    @Processor
    public List<Gist> getGists(@Optional String user) throws IOException {
        return serviceFactory.getGistService().getGists(getUser(user));
    }

    /**
     * Creates a comment on the specified gist id
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param gistId  id of the gist
     * @param comment comment to create in the gist
     * @return a new comment for the gist
     * @throws IOException
     */
    @Processor
    public Comment createGistComment(String gistId, String comment) throws IOException {
        return serviceFactory.getGistService().createComment(gistId, comment);
    }

    /**
     * Returns a list of comments for the given gist
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param gistId id of the gist
     * @return a list with the comments of the given gist
     * @throws IOException
     */
    @Processor
    public List<Comment> getGistComments(String gistId) throws IOException {
        return serviceFactory.getGistService().getComments(gistId);
    }

    /**
     * Deletes the given gist
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param gistId id of the gist
     * @throws IOException
     */
    @Processor
    public void deleteGist(String gistId) throws IOException {
        serviceFactory.getGistService().deleteGist(gistId);
    }

    /**
     * Returns the comment according to the given id
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param commentId id of the comment to be retrieved
     * @return a comment corresponding to the given id
     * @throws IOException
     */
    @Processor
    public Comment getGistComment(long commentId) throws IOException {
        return serviceFactory.getGistService().getComment(commentId);
    }

    /**
     * Deletes the given comment
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param commentId id of the comment
     * @throws IOException
     */
    @Processor
    public void deleteGistComment(long commentId) throws IOException {
        serviceFactory.getGistService().deleteComment(commentId);
    }

    /**
     * Updates the given comment
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param commentId id of the comment
     * @param body      new body of the comment
     * @return returns the updated comment
     * @throws IOException
     */
    @Processor
    public Comment editGistComment(long commentId, String body) throws IOException {
        Comment comment = new Comment();
        comment.setId(commentId);
        comment.setBody(body);

        return serviceFactory.getGistService().editComment(comment);
    }

    /**
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     * <p/>
     * Star the gist with the given id
     *
     * @param gistId id of the gist to be starred
     * @throws IOException
     */
    @Processor
    public void starGist(String gistId) throws IOException {
        serviceFactory.getGistService().starGist(gistId);
    }

    /**
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     * <p/>
     * Unstar the gist with the given id
     *
     * @param gistId id of the gist to be unstarred
     * @throws IOException
     */
    @Processor
    public void unstarGist(String gistId) throws IOException {
        serviceFactory.getGistService().unstarGist(gistId);
    }

    /**
     * Returns whether the gist is starred or not
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param gistId id of the gist
     * @return returns true if the gist is starred, false otherwise
     * @throws IOException
     */
    @Processor
    public boolean isStarred(String gistId) throws IOException {
        return serviceFactory.getGistService().isStarred(gistId);
    }

    /**
     * Forks the given gist
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param gistId id of the gist to be forked
     * @return returns the forked gist
     * @throws IOException
     */
    @Processor
    public Gist forkGist(String gistId) throws IOException {
        return serviceFactory.getGistService().forkGist(gistId);
    }

    /**
     * Returns a list of labels for the given repository and user
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param user       the owner of the repository, leave empty to use {@link this#user}
     * @param repository the name of the repository
     * @return a list of labels for the given repository and user
     * @throws IOException
     */
    @Processor
    public List<Label> getLabels(@Optional String user, String repository) throws IOException {
        return serviceFactory.getLabelService().getLabels(getUser(user), repository);
    }

    /**
     * Returns a single label
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param user       the owner of the repository, leave empty to use {@link this#user}
     * @param repository the name of the repository
     * @param label      the label id
     * @return the label associated to the given id
     * @throws IOException
     */
    @Processor
    public Label getLabel(@Optional String user, String repository, String label) throws IOException {
        return serviceFactory.getLabelService().getLabel(getUser(user), repository, label);
    }

    /**
     * Deletes the given label
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param user       the owner of the repository, leave empty to use {@link this#user}
     * @param repository the name of the repository
     * @param label      the label id
     * @throws IOException
     */
    @Processor
    public void deleteLabel(@Optional String user, String repository, String label) throws IOException {
        serviceFactory.getLabelService().deleteLabel(getUser(user), repository, label);
    }

    /**
     * Creates a new label
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param user       the owner of the repository, leave empty to use {@link this#user}
     * @param repository the name of the repository
     * @param name       the name of the label
     * @param color      the color of the label, a 6 character hex code, without a leading #
     * @return returns a new Label
     * @throws IOException
     */
    @Processor
    public Label createLabel(@Optional String user, String repository, String name, String color) throws IOException {
        Label label = new Label();
        label.setName(name);
        label.setColor(color);

        return serviceFactory.getLabelService().createLabel(getUser(user), repository, label);
    }

    // TODO add set labels method

    /**
     * Returns a list of milestones for the given repository
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param user       the owner of the repository, leave empty to use {@link this#user}
     * @param repository the name of the repository
     * @param state      state of the milestone, open or closed
     * @return s list of milestones for the given repository
     * @throws IOException
     */
    @Processor
    public List<Milestone> getMilestones(@Optional String user, String repository, String state) throws IOException {
        return serviceFactory.getMilestoneService().getMilestones(getUser(user), repository, state);
    }


    /**
     * Returns a single milestone
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param user       the owner of the repository, leave empty to use {@link this#user}
     * @param repository the name of the repository
     * @param number     milestone number
     * @return returns a single milestone
     * @throws IOException
     */
    @Processor
    public Milestone getMilestone(@Optional String user, String repository, String number) throws IOException {
        return serviceFactory.getMilestoneService().getMilestone(getUser(user), repository, number);
    }


    /**
     * Deletes a given milestone
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param user       the owner of the repository, leave empty to use {@link this#user}
     * @param repository the name of the repository
     * @param number     number of the milestone
     * @throws IOException
     */
    @Processor
    public void deleteMilestone(@Optional String user, String repository, String number) throws IOException {
        serviceFactory.getMilestoneService().deleteMilestone(getUser(user), repository, number);
    }

    /**
     * Creates a new milestone
     * </p>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param user        the owner of the repository, leave empty to use {@link this#user}
     * @param repository  the name of the repository
     * @param title       the title of the milestone
     * @param state       the state of the milestone, open or closed,  by default is open
     * @param description the description of the milestone
     * @param dueOn       when the milestone is due
     * @return a new milestone with the given parameters
     * @throws IOException
     */
    @Processor
    public Milestone createMilestone(@Optional String user, String repository, String title, @Optional String state,
                                     @Optional String description, @Optional Date dueOn) throws IOException {
        Milestone milestone = new Milestone();
        milestone.setTitle(title);
        milestone.setState(state);
        milestone.setDueOn(dueOn);
        milestone.setDescription(description);

        return serviceFactory.getMilestoneService().createMilestone(getUser(user), repository, milestone);
    }

    /**
     * Get user with given login name
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param loginName the login name of the user to look up
     * @return a {@link User} instance
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/users/">Get a single user</a>
     */
    @Processor
    public User getUserByLoginName(String loginName) throws IOException {
        return serviceFactory.getUserService().getUser(loginName);
    }

    /**
     * Get the currently authenticated user
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @return a {@link User} instance representing the current user
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/users/">Get the authenticated user</a>
     */
    @Processor
    public User getCurrentUser() throws IOException {
        return serviceFactory.getUserService().getUser();
    }

    /**
     * Updates the currently authenticated user using the given attributes. Only provide values for the attributes
     * you want to change.
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param name     a the name for the current user
     * @param email    a publicly visibile email address for the current user
     * @param blog     a blog for the current user
     * @param company  a company for the current user
     * @param location a location for the current user
     * @param hireable whether the current user is hireable
     * @return a {@link User} instance representing the current user
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/users/">Update the authenticated user</a>
     */
    @Processor
    public User updateCurrentUser(@Optional String name, @Optional String email, @Optional String blog, @Optional String company,
                                  @Optional String location, @Optional Boolean hireable) throws IOException {
        User currentUser = getCurrentUser();
        if (name != null) {
            currentUser.setName(name);
        }
        if (email != null) {
            currentUser.setEmail(email);
        }
        if (blog != null) {
            currentUser.setBlog(blog);
        }
        if (company != null) {
            currentUser.setCompany(company);
        }
        if (location != null) {
            currentUser.setLocation(location);
        }
        if (hireable != null) {
            currentUser.setHireable(hireable);
        }
        return serviceFactory.getUserService().editUser(currentUser);
    }

    /**
     * Returns a list of followers for given user, if no one is provided the current authenticated user will be used
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param user the user for which to get the followers, leave empty to use current user
     * @return a collection of {@link User} that follow the current user
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/users/followers/">List followers of a user</a>
     */
    @Processor
    public List<User> getFollowers(@Optional String user) throws IOException {
        return serviceFactory.getUserService().getFollowers(getUser(user));
    }

    /**
     * Returns a list users following the given user, if no one is provided the current authenticated user will be used
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param user the user for which to get who is following, leave empty to use current user
     * @return a collection of {@link User} the user is following
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/users/followers/">List users following another user</a>
     */
    @Processor
    public List<User> getFollowing(@Optional String user) throws IOException {
        return serviceFactory.getUserService().getFollowing(getUser(user));
    }

    /**
     * Returns wether the authenticated user is following the given user
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param user the user to check
     * @return wether the authenticated user is following the given user
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/users/followers/">Check if you are following a user</a>
     */
    @Processor
    public boolean isFollowing(String user) throws IOException {
        return serviceFactory.getUserService().isFollowing(user);
    }

    /**
     * Make the currently authenticated user follow the given user
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param user the user to follow
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/users/followers/">Follow a user</a>
     */
    @Processor
    public void follow(String user) throws IOException {
        serviceFactory.getUserService().follow(user);
    }

    /**
     * Make the currently authenticated user unfollow the given user
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param user the user to unfollow
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/users/followers/">Unfollow a user</a>
     */
    @Processor
    public void unfollow(String user) throws IOException {
        serviceFactory.getUserService().unfollow(user);
    }

    /**
     * Get all e-mail addresses for the currently authenticated user
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @return list of e-mail address
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/users/emails/">List email addresses for a user</a>
     */
    @Processor
    public List<String> getEmails() throws IOException {
        return serviceFactory.getUserService().getEmails();
    }

    /**
     * Add one or more e-mail addresses to the currently authenticated user's account
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param emails the email addresses to add
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/users/emails/">Add email address(es)</a>
     */
    @Processor
    public void addEmails(List<String> emails) throws IOException {
        serviceFactory.getUserService().addEmail(emails.toArray(new String[emails.size()]));
    }

    /**
     * Removes one or more e-mail addresses to the currently authenticated user's account
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param emails the email addresses to add
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/users/emails/">Delete email address(es)</a>
     */
    @Processor
    public void removeEmails(List<String> emails) throws IOException {
        serviceFactory.getUserService().removeEmail(emails.toArray(new String[emails.size()]));
    }

    /**
     * Get all public keys for currently authenticated user
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @return non-null list of {@link Key}
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/users/keys/">List public keys for a user</a>
     */
    @Processor
    public List<Key> getKeys() throws IOException {
        return serviceFactory.getUserService().getKeys();
    }

    /**
     * Get key with given id
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param id the id of the key of obtain
     * @return a {@link Key} instance
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/users/keys/">Get a single public key</a>
     */
    @Processor
    public Key getKey(int id) throws IOException {
        return serviceFactory.getUserService().getKey(id);
    }

    /**
     * Create key for currently authenticated user
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param title the title of the new key
     * @param key   the new key
     * @return the created {@link Key}
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/users/keys/">Create a public key</a>
     */
    @Processor
    public Key createKey(String title, String key) throws IOException {
        Key newKey = new Key();
        newKey.setTitle(title);
        newKey.setKey(key);
        return serviceFactory.getUserService().createKey(newKey);
    }

    /**
     * Edit key for currently authenticated user
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param keyId the id of the key to edit
     * @param title a new title for the key
     * @param key   a new key
     * @return edited {@link Key}
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/users/keys/">Update a public key</a>
     */
    @Processor
    public Key editKey(int keyId, @Optional String title, @Optional String key) throws IOException {
        Key keyToEdit = getKey(keyId);
        if (title != null) {
            keyToEdit.setTitle(title);
        }
        if (key != null) {
            keyToEdit.setKey(key);
        }
        return serviceFactory.getUserService().editKey(keyToEdit);
    }

    /**
     * Delete key with given id
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param id the id of the key to delete
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/users/keys/">Delete a public key</a>
     */
    @Processor
    public void deleteKey(int id) throws IOException {
        serviceFactory.getUserService().deleteKey(id);
    }

    /**
     * Get team with given id
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param id the id of the team
     * @return a {@link Team} instance
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/orgs/teams/">Get team</a>
     */
    @Processor
    public Team getTeam(int id) throws IOException {
        return serviceFactory.getTeamService().getTeam(id);
    }

    /**
     * Get all teams in the given organization
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param organization the organization for which te get the teams associated with
     * @return list of {@link Team}
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/orgs/teams/">List teams</a>
     */
    @Processor
    public List<Team> getTeamsForOrg(String organization) throws IOException {
        return serviceFactory.getTeamService().getTeams(organization);
    }

    /**
     * Create the given team
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param organization   the organization
     * @param teamName       the team name
     * @param teamPermission the team's {@link TeamPermission}
     * @param repoNames      the associated repository names
     * @return the created {@link Team}
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/orgs/teams/">Create team</a>
     */
    @Processor
    public Team createTeam(String organization, String teamName, @Optional @Default("PULL") TeamPermission teamPermission,
                           @Optional List<String> repoNames) throws IOException {
        Team team = new Team();
        team.setName(teamName);
        team.setPermission(teamPermission.toString());
        if (repoNames != null) {
            return serviceFactory.getTeamService().createTeam(organization, team, repoNames);
        } else {
            return serviceFactory.getTeamService().createTeam(organization, team);
        }
    }

    /**
     * Edit the given team. Only provide values for the attributes you want to update.
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param id             the id of the team to edit
     * @param name           the new name of the team
     * @param teamPermission the new {@link TeamPermission} for the team
     * @return the edited {@link Team}
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/orgs/teams/">Edit team</a>
     */
    @Processor
    public Team editTeam(int id, @Optional String name, @Optional TeamPermission teamPermission) throws IOException {
        Team team = getTeam(id);
        if (name != null) {
            team.setName(name);
        }
        if (teamPermission != null) {
            team.setPermission(teamPermission.toString());
        }
        return serviceFactory.getTeamService().editTeam(team);
    }

    /**
     * Delete the team with the given id
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param id the id of the team to delete.
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/orgs/teams/">Delete team</a>
     */
    @Processor
    public void deleteTeam(int id) throws IOException {
        serviceFactory.getTeamService().deleteTeam(id);
    }

    /**
     * Get members of team with given id
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param id the team id
     * @return team members
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/orgs/teams/">List members</a>
     */
    @Processor
    public List<User> getTeamMembers(int id) throws IOException {
        return serviceFactory.getTeamService().getMembers(id);
    }

    /**
     * Is the given user a member of the team with the given id
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param id   the team id
     * @param user the user name
     * @return true if member, false if not member
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/orgs/teams/">Get if a user is a public member</a>
     */
    @Processor
    public boolean isTeamMember(int id, String user) throws IOException {
        return serviceFactory.getTeamService().isMember(id, user);
    }

    /**
     * Add given user to team with given id
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param id   the team id
     * @param user the user name
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/orgs/teams/">Add a member</a>
     */
    @Processor
    public void addTeamMember(int id, String user) throws IOException {
        serviceFactory.getTeamService().addMember(id, user);
    }

    /**
     * Remove given user from team with given id
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param id   the team id
     * @param user the user name
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/orgs/teams/">Remove a member</a>
     */
    @Processor
    public void removeTeamMember(int id, String user) throws IOException {
        serviceFactory.getTeamService().removeMember(id, user);
    }

    /**
     * Get all repositories for given team
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param id the team id
     * @return non-null list of repositories
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/orgs/teams/">List team repos</a>
     */
    @Processor
    public List<Repository> getTeamRepositories(int id) throws IOException {
        return serviceFactory.getTeamService().getRepositories(id);
    }

    /**
     * Add repository to team
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param id    the team id
     * @param owner the owner of the repository
     * @param name  the name of the repository
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/orgs/teams/">Add team repo</a>
     */
    @Processor
    public void addTeamRepository(int id, String owner, String name) throws IOException {
        serviceFactory.getTeamService().addRepository(id, RepositoryId.create(owner, name));
    }

    /**
     * Remove repository from team
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param id    the team id
     * @param owner the owner of the repository
     * @param name  the name of the repository
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/orgs/teams/">Remove team repo</a>
     */
    @Processor
    public void removeTeamRepository(int id, String owner, String name) throws IOException {
        serviceFactory.getTeamService().removeRepository(id, RepositoryId.create(owner, name));
    }

    /**
     * Get repositories for the currently authenticated user
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param filterData data to filter repos, if non is specified all repos will be returned
     * @return list of {@link Repository}
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/repos"></a>
     */
    @Processor
    public List<Repository> getRepositories(@Optional Map<String, String> filterData) throws IOException {
        return serviceFactory.getRepositoryService().getRepositories(filterData);
    }

    /**
     * Get repositories for the given user
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param user the user for which to get the repositories for
     * @return list of {@link Repository}
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/repos"></a>
     */
    @Processor
    public List<Repository> getRepositoriesForUser(String user) throws IOException {
        return serviceFactory.getRepositoryService().getRepositories(user);
    }

    /**
     * Get organization repositories for the given organization
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param organization the organization for which to get the repositories for
     * @param filterData   data to filter repos, if non is specified all repos will be returned
     * @return list of {@link Repository}
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/repos"></a>
     */
    @Processor
    public List<Repository> getOrgRepositories(String organization, @Optional Map<String, String> filterData) throws IOException {
        return serviceFactory.getRepositoryService().getOrgRepositories(organization, filterData);
    }

    /**
     * Create a new repository
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param name         the name of the new repository
     * @param description  a description for the new repository
     * @param isPrivate    true to create a private repository, false to create a public one. Creating private repositories requires a paid GitHub account. Default is false.
     * @param hasIssues    true to enable issues for this repository, false to disable them. Default is true.
     * @param hasWiki      true to enable the wiki for this repository, false to disable it. Default is true.
     * @param hasDownloads true to enable downloads for this repository, false to disable them. Default is true.
     * @return the created {@link Repository}
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/repos">Create</a>
     */
    @Processor
    public Repository createRepository(String name, @Optional String description, @Optional @Default("false") boolean isPrivate,
                                       @Optional @Default("true") boolean hasIssues, @Optional @Default("true") boolean hasWiki,
                                       @Optional @Default("true") boolean hasDownloads) throws IOException {
        Repository repository = new Repository();
        repository.setName(name);
        repository.setDescription(description);
        repository.setPrivate(isPrivate);
        repository.setHasIssues(hasIssues);
        repository.setHasWiki(hasWiki);
        repository.setHasDownloads(hasDownloads);
        return serviceFactory.getRepositoryService().createRepository(repository);
    }

    /**
     * Create a new repository for the given organization
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param organization the organization for the new repository
     * @param name         the name of the new repository
     * @param description  a description for the new repository
     * @param isPrivate    true to create a private repository, false to create a public one. Creating private repositories requires a paid GitHub account. Default is false.
     * @param hasIssues    true to enable issues for this repository, false to disable them. Default is true.
     * @param hasWiki      true to enable the wiki for this repository, false to disable it. Default is true.
     * @param hasDownloads true to enable downloads for this repository, false to disable them. Default is true.
     * @return the created {@link Repository}
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/repos">Create</a>
     */
    @Processor
    public Repository createRepositoryForOrg(String organization, String name, @Optional String description, @Optional @Default("false") boolean isPrivate,
                                             @Optional @Default("true") boolean hasIssues, @Optional @Default("true") boolean hasWiki,
                                             @Optional @Default("true") boolean hasDownloads) throws IOException {
        Repository repository = new Repository();
        repository.setName(name);
        repository.setDescription(description);
        repository.setPrivate(isPrivate);
        repository.setHasIssues(hasIssues);
        repository.setHasWiki(hasWiki);
        repository.setHasDownloads(hasDownloads);
        return serviceFactory.getRepositoryService().createRepository(organization, repository);
    }

    /**
     * Get repository
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param owner the name of the user that owns the repository
     * @param name  the name of the repository
     * @return repository
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/repos"></a>
     */
    @Processor
    public Repository getRepository(String owner, String name) throws IOException {
        return serviceFactory.getRepositoryService().getRepository(owner, name);
    }

    /**
     * Edit given repository. Only provide values for the attributes you need to change.
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param owner        the owner of the repository
     * @param name         the name of the repository
     * @param description  a new description for the repository
     * @param isPrivate    true to turn it into a private repository, false to make it public. Private repositories require a paid GitHub account.
     * @param hasIssues    true to enable issues for this repository, false to disable them.
     * @param hasWiki      true to enable the wiki for this repository, false to disable it.
     * @param hasDownloads true to enable downloads for this repository, false to disable them.
     * @return the edited {@link Repository}
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/repos"></a>
     */
    @Processor
    public Repository editRepository(String owner, String name, @Optional String description, @Optional Boolean isPrivate,
                                     @Optional Boolean hasIssues, @Optional Boolean hasWiki, @Optional Boolean hasDownloads) throws IOException {
        Repository repositoryToEdit = getRepository(owner, name);
        if (description != null) {
            repositoryToEdit.setDescription(description);
        }
        if (isPrivate != null) {
            repositoryToEdit.setPrivate(isPrivate);
        }
        if (hasIssues != null) {
            repositoryToEdit.setHasIssues(hasIssues);
        }
        if (hasWiki != null) {
            repositoryToEdit.setHasWiki(hasWiki);
        }
        if (hasDownloads != null) {
            repositoryToEdit.setHasDownloads(hasDownloads);
        }
        return serviceFactory.getRepositoryService().editRepository(repositoryToEdit);
    }

    /**
     * Get all the forks of the given repository
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param owner the owner of the repository
     * @param name  the name of the repository
     * @return non-null but possibly empty list of repository
     * @throws IOException
     */
    @Processor
    public List<Repository> getForks(String owner, String name) throws IOException {
        return serviceFactory.getRepositoryService().getForks(RepositoryId.create(owner, name));
    }

    /**
     * Fork given repository into new repository under the currently
     * authenticated user.
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param owner the owner of the repository
     * @param name  the name of the repository
     * @return forked repository
     * @throws IOException
     */
    @Processor
    public Repository forkRepository(String owner, String name) throws IOException {
        return serviceFactory.getRepositoryService().forkRepository(RepositoryId.create(owner, name));
    }

    /**
     * Fork given repository into new repository.
     * <p/>
     * The new repository will be under the given organization if non-null, else
     * it will be under the currently authenticated user.
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param organization the organization where the new repository will be
     * @param owner        the owner of the repository
     * @param name         the name of the repository
     * @return forked repository
     * @throws IOException
     */
    @Processor
    public Repository forkRepositoryForOrg(String organization, String owner, String name) throws IOException {
        return serviceFactory.getRepositoryService().forkRepository(RepositoryId.create(owner, name), organization);
    }

    /**
     * Get languages used in given repository
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param owner the owner of the repository
     * @param name  the name of the repository
     * @return map of language names mapped to line counts
     * @throws IOException\
     * @api.doc <a href="http://developer.github.com/v3/repos"></a>
     */
    @Processor
    public Map<String, Long> getLanguages(String owner, String name) throws IOException {
        return serviceFactory.getRepositoryService().getLanguages(RepositoryId.create(owner, name));
    }

    /**
     * Get branches in given repository
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param owner the owner of the repository
     * @param name  the name of the repository
     * @return list of branches
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/repos"></a>
     */
    @Processor
    public List<RepositoryBranch> getBranches(String owner, String name) throws IOException {
        return serviceFactory.getRepositoryService().getBranches(RepositoryId.create(owner, name));
    }

    /**
     * Get tags in given repository
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param owner the owner of the repository
     * @param name  the name of the repository
     * @return list of tags
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/repos"></a>
     */
    @Processor
    public List<RepositoryTag> getTags(String owner, String name) throws IOException {
        return serviceFactory.getRepositoryService().getTags(RepositoryId.create(owner, name));
    }

    /**
     * Get contributors to repository
     * <p/>
     * {@sample.xml ../../../doc/GitHub-connector.xml.sample github:my-processor}
     *
     * @param owner            the owner of the repository
     * @param name             the name of the repository
     * @param includeAnonymous whether to include anonymus contributors
     * @return list of contributors
     * @throws IOException
     * @api.doc <a href="http://developer.github.com/v3/repos"></a>
     */
    @Processor
    public List<Contributor> getContributors(String owner, String name, @Optional @Default("false") boolean includeAnonymous) throws IOException {
        return serviceFactory.getRepositoryService().getContributors(RepositoryId.create(owner, name), includeAnonymous);
    }

    public void setuser(String user) {
        this.user = user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    private String getUser(String user) {
        return user != null ? user : this.user;
    }
}